import logging
import uuid
from typing import Any

import httpx

logger = logging.getLogger(__name__)


class GitLabService:
	def __init__(self, token: str, base_url: str = "https://gitlab.com/api/v4"):
		self.base_url = base_url.rstrip("/")
		self.headers = {"Private-Token": token}

	async def create_mr(self, project_id: str, code: str, title: str) -> dict[str, Any]:
		"""
		Creates a unique branch, commits the code, and opens a Merge Request.
		"""
		async with httpx.AsyncClient() as client:
			branch_name = f"feature/testops-{uuid.uuid4().hex[:8]}"

			branch_res = await client.post(
				f"{self.base_url}/projects/{project_id}/repository/branches",
				headers=self.headers,
				json={"branch": branch_name, "ref": "main"}
			)
			if branch_res.status_code != 201:
				logger.error(f"Failed to create branch: {branch_res.text}")
				raise Exception(f"GitLab Branch Error: {branch_res.text}")

			file_path = f"tests/test_{uuid.uuid4().hex[:6]}.py"
			commit_payload = {
				"branch": branch_name,
				"commit_message": f"Add generated test: {title}",
				"actions": [
					{
						"action": "create",
						"file_path": file_path,
						"content": code
					}
				]
			}

			commit_res = await client.post(
				f"{self.base_url}/projects/{project_id}/repository/commits",
				headers=self.headers,
				json=commit_payload
			)
			if commit_res.status_code != 201:
				raise Exception(f"GitLab Commit Error: {commit_res.text}")

			mr_payload = {
				"source_branch": branch_name,
				"target_branch": "main",
				"title": f"TestOps Auto: {title}",
				"description": "Test case generated by TestOps Evolution Forge AI Agent.",
				"remove_source_branch": True
			}
			mr_res = await client.post(
				f"{self.base_url}/projects/{project_id}/merge_requests",
				headers=self.headers,
				json=mr_payload
			)
			if mr_res.status_code != 201:
				raise Exception(f"GitLab MR Error: {mr_res.text}")

			data = mr_res.json()
			return {
				"status": "success",
				"mr_url": data.get("web_url"),
				"branch": branch_name
			}
