from typing import List, Optional
from pydantic import BaseModel, Field
from src.app.domain.enums import ProcessingStatus, TestType

class TestGenerationRequest(BaseModel):
    user_request: str = Field(
        ..., 
        description="Natural language description of the test case or a URL to Swagger/OpenAPI spec",
        examples=["Verify the login functionality", "https://petstore.swagger.io/v2/swagger.json"]
    )
    model_name: Optional[str] = Field(
        None,
        description="Specific LLM model to use (e.g. Qwen/Qwen2.5-Coder-32B-Instruct)"
    )

class TestGenerationResponse(BaseModel):
    status: ProcessingStatus = Field(..., description="Current workflow status")
    test_type: Optional[TestType] = Field(None, description="Detected test type (UI/API)")
    generated_code: Optional[str] = Field(None, description="Final Python code generated by the agent")
    test_plan: List[str] = Field(default=[], description="Step-by-step test plan created by Analyst")
    logs: List[str] = Field(default=[], description="Execution logs from all agents")
    error: Optional[str] = Field(None, description="Error message if generation failed")
