from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

from src.app.domain.enums import ProcessingStatus, TestType


class TestGenerationRequest(BaseModel):
	user_request: str = Field(
		...,
		description="Natural language description of the test case or a URL to Swagger/OpenAPI spec",
		examples=["Verify the login functionality", "https://petstore.swagger.io/v2/swagger.json"]
	)
	model_name: str | None = Field(
		None,
		description="Specific LLM model to use (e.g. Qwen/Qwen2.5-Coder-32B-Instruct)"
	)


class NotificationSchema(BaseModel):
	id: int
	message: str
	related_run_id: int | None = None
	is_read: bool
	created_at: datetime

	class Config:
		from_attributes = True


class TestGenerationResponse(BaseModel):
	status: ProcessingStatus = Field(..., description="Current workflow status")
	test_type: TestType | None = Field(None, description="Detected test type (UI/API)")
	generated_code: str | None = Field(None, description="Final Python code generated by the agent")
	test_plan: list[str] = Field(default=[], description="Step-by-step test plan created by Analyst")
	logs: list[str] = Field(default=[], description="Execution logs from all agents")
	error: str | None = Field(None, description="Error message if generation failed")


class ChatMessageRequest(BaseModel):
	message: str
	model_name: str | None = None
	run_id: int | None = None  # If None, creates new run


class ApprovalRequest(BaseModel):
	run_id: int
	approved: bool
	feedback: str | None = None  # Optional edited test plan text
